// Code generated by MockGen. DO NOT EDIT.
// Source: types.go
//
// Generated by this command:
//
//	mockgen -source=types.go -destination=mocks_test.go -package=main
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	reflect "reflect"

	container "github.com/docker/docker/api/types/container"
	events "github.com/docker/docker/api/types/events"
	gomock "go.uber.org/mock/gomock"
)

// MockContainerLister is a mock of ContainerLister interface.
type MockContainerLister struct {
	ctrl     *gomock.Controller
	recorder *MockContainerListerMockRecorder
	isgomock struct{}
}

// MockContainerListerMockRecorder is the mock recorder for MockContainerLister.
type MockContainerListerMockRecorder struct {
	mock *MockContainerLister
}

// NewMockContainerLister creates a new mock instance.
func NewMockContainerLister(ctrl *gomock.Controller) *MockContainerLister {
	mock := &MockContainerLister{ctrl: ctrl}
	mock.recorder = &MockContainerListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContainerLister) EXPECT() *MockContainerListerMockRecorder {
	return m.recorder
}

// ContainerList mocks base method.
func (m *MockContainerLister) ContainerList(ctx context.Context, options container.ListOptions) ([]container.Summary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainerList", ctx, options)
	ret0, _ := ret[0].([]container.Summary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContainerList indicates an expected call of ContainerList.
func (mr *MockContainerListerMockRecorder) ContainerList(ctx, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainerList", reflect.TypeOf((*MockContainerLister)(nil).ContainerList), ctx, options)
}

// MockEventProducer is a mock of EventProducer interface.
type MockEventProducer struct {
	ctrl     *gomock.Controller
	recorder *MockEventProducerMockRecorder
	isgomock struct{}
}

// MockEventProducerMockRecorder is the mock recorder for MockEventProducer.
type MockEventProducerMockRecorder struct {
	mock *MockEventProducer
}

// NewMockEventProducer creates a new mock instance.
func NewMockEventProducer(ctrl *gomock.Controller) *MockEventProducer {
	mock := &MockEventProducer{ctrl: ctrl}
	mock.recorder = &MockEventProducerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventProducer) EXPECT() *MockEventProducerMockRecorder {
	return m.recorder
}

// Events mocks base method.
func (m *MockEventProducer) Events(ctx context.Context, options events.ListOptions) (<-chan events.Message, <-chan error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Events", ctx, options)
	ret0, _ := ret[0].(<-chan events.Message)
	ret1, _ := ret[1].(<-chan error)
	return ret0, ret1
}

// Events indicates an expected call of Events.
func (mr *MockEventProducerMockRecorder) Events(ctx, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Events", reflect.TypeOf((*MockEventProducer)(nil).Events), ctx, options)
}
